version: "3.8"

services:
    db:
        container_name: postgress_race
        image: postgres:15.2
        restart: always
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - ./db_backup:/var/lib/postgresql/data/
        expose:
            - ${DB_PORT}
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}

    cache:
        container_name: radis_cache
        image: redis:6.2-alpine
        restart: always
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
        volumes:
            - cache:/data

volumes:
    cache:
        driver: local
